NAME: 'sequential_c_rid_trans'

TRAIN:
    img_size: 256
    model_id_dn: 291000
    multi_scale: True
    batch_size: 2
    num_workers: 4
    if_cuda: True
    loss_func_dn: 'MSELoss'
    loss_func_seg: 'WeightedBCELoss'
    random_seed: 555
    resume: True
    resume_path_dn: '/model/ZCWANG007/jdas/dn/c/ridnet'
    if_valid: True
    best_voi: 1.66
    opt_type: 'adam'  # sgd
    lr_mode: 'fixed'
    min_valid: 0
   
    total_iters: 400000
    warmup_iters: 0
    base_lr: 0.0001
    end_lr: 0.0001
    display_freq: 100
    show_freq: 1000
    valid_freq: 1000
    save_freq: 100000
    decay_iters: 10000
    weight_decay: ~
    power: 0.9

 

    cache_path: '/output/caches/'   # 
    save_path: '/output/models/'    #  
    record_path: '/output/logs/'    # 
    valid_path: '/output/valid/'    # 
        
time:     0

VALID: 0


DATA:
    root_path : '/braindat/lab/chenyd/DATASET' # ../data, /data/weih527
    data_name: 'CREMIC'
    num_train: 75   
    num_valid: 50
    num_test: 50
    padding: True
    separate_weight: True
    crop_size:
        - 256
        - 256
    shifts:
        - 1
        - 3
        - 5
        - 9
        - 15
    neighbor: 4
    strides: 
        - 5
        - 5
    noiseL: 50
    noise_type: 'scaled'
    noise_std: 0.2
    blind: False
    mask: False
    mask_ratio: 0.5
 
MODEL:

    input_nc: 1
    output_nc: 1
    if_sigmoid: False
    emd: 16
    filters: 
        - 16
        - 32
        - 64
        - 128
        - 256
    finetuning: False


    MODEL_denoise:
        model_type: 'ridnet'
        input_nc: 1
        output_nc: 1
        if_sigmoid: False

MODEL_seg:
    num_classes: 10
    n_skip: 3
    vit_name: R50-ViT-B_16
    vit_patches_size: 16

TEST:
    pad: 15
    model_name: ''