NAME: 'test_dms_ac4'

TRAIN:
    model_id: 284000
    multi_scale: True
    batch_size: 32
    num_workers: 4
    if_cuda: True
    loss_func_dn: 'MSELoss'
    loss_func_seg: 'WeightedBCELoss'
    weight_seg: 1
    weight_denoise: 1
    random_seed: 555
    resume: True
    resume_type: 'dn'
    resume_path: '/model/ZCWANG007/jdas/dms/ac34'
    if_valid: True
    
    opt_type: 'adam'  # sgd
    lr_mode: 'fixed'
    min_valid: 0
   
    total_iters: 400000
    warmup_iters: 0
    base_lr: 0.0001
    end_lr: 0.0001
    display_freq: 100
    show_freq: 1000
    valid_freq: 1000
    save_freq: 100000
    decay_iters: 10000
    weight_decay: ~
    power: 0.9

 

    cache_path: '/output/caches/'   # 
    save_path: '/output/models/'    #  
    record_path: '/output/logs/'    # 
    valid_path: '/output/valid/'    # 
        
time:     0

VALID: 0


DATA:
    root_path : '/braindat/lab/chenyd/DATASET' # ../data, /data/weih527
    data_name: 'AC3/4'
    num_train: 256
    num_valid: 100
    num_test: 50
    padding: True
    separate_weight: True
    crop_size:
        - 256
        - 256
    shifts:
        - 1
        - 3
        - 5
        - 9
        - 15
    neighbor: 4
    strides: 
        - 5
        - 5
    noiseL: 50
    noise_type: 'scaled'
    noise_std: 0.2
    blind: False
    mask: False
    mask_ratio: 0.5
 
MODEL:

    input_nc: 1
    output_nc: 1
    if_sigmoid: False
    emd: 16
    filters: 
        - 16
        - 32
        - 64
        - 128
        - 256
    finetuning: False


MODEL_seg:
    model_type: 'seg'



TEST:
    pad: 15
    model_name: ''